openapi: 3.0.1
info:
  title: API Documentation
  version: Alpha
tags:
  - name: Dataset
  - name: Properties
    description: organizations, resources, tags and themes.
  - name: SQL Query
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    uuid:
      name: "uuid"
      in: path
      description: A uuid from a dataset or a property
      required: true
      schema:
        type: string
    property:
      name: "property"
      in: path
      description: Property of a dataset
      required: true
      schema:
        type: string
    query:
      name: "query"
      in: path
      description: SQL query
      required: true
      schema:
        type: string
  schemas:
    responseMessage:
      type: object
      required:
        - message
    responseEndpointIdentifier:
      type: object
      required:
        - endpoint
        - identifier
    # @TODO: Load directly from dkan2's schema/collections/dataset.json schema
    Dataset:
      type: object
      required:
        - title
        - description
        - identifier
        - accessLevel
      properties:
        title:
          type: string
        description:
          type: string
        identifier:
          type: string
        accessLevel:
          type: string
          enum:
            - public
            - restricted public
            - non-public
paths:
  /api/v1/dataset:
    get:
      summary: Get all datasets
      tags:
        - Dataset
      responses:
        200:
          description: Ok
    post:
      summary: Create a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      responses:
        201:
          description: Created
  /api/v1/dataset/{uuid}:
    get:
      summary: Get this dataset
      tags:
        - Dataset
      parameters:
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Ok
    put:
      summary: Replace a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      parameters:
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Ok
    patch:
      summary: Update a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      parameters:
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Ok
    delete:
      summary: Delete a dataset
      tags:
        - Dataset
      security:
        - basicAuth: []
      parameters:
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Dataset has been deleted
  /api/v1/{property}:
    get:
      summary: Get properties
      tags:
        - Properties
      parameters:
        - name: "property"
          in: "path"
          description: "Dataset property"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
    post:
      summary: Create a property
      tags:
        - Properties
      security:
        - basicAuth: []
      parameters:
        - name: "property"
          in: "path"
          description: "Dataset property"
          required: true
          schema:
            type: string
      responses:
        201:
          description: Created
  /api/v1/{property}/{uuid}:
    get:
      summary: Get a property
      tags:
        - Properties
      parameters:
        - $ref: "#/components/parameters/property"
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Ok
    put:
      summary: Replace a property
      tags:
        - Properties
      security:
        - basicAuth: []
      parameters:
        - $ref: "#/components/parameters/property"
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Ok
    patch:
      summary: Update a property
      tags:
        - Properties
      security:
        - basicAuth: []
      parameters:
        - $ref: "#/components/parameters/property"
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Ok
    delete:
      summary: Delete a property
      tags:
        - Properties
      security:
        - basicAuth: []
      parameters:
        - $ref: "#/components/parameters/property"
        - $ref: "#/components/parameters/uuid"
      responses:
        200:
          description: Organization has been deleted
  /api/v1/sql/{query}:
    get:
      summary: Query resources in datastore
      description: Interact with resources in the datastore using an SQL-like syntax.
      tags:
        - SQL Query
      parameters:
        - $ref: "#/components/parameters/query"
      responses:
        200:
          description: Ok
