<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_load().
 */
function dkan_data_node_load(array $entities) {

  foreach ($entities as $entity) {
    if ($entity->bundle() == "data" && $entity->field_data_type->value == "dataset") {
      // Temporarily save the raw json metadata, for later use.
      $metadata_string = $entity->get('field_json_metadata')->value;
      $entity->referenced_metadata = $metadata_string;
      // Dereference dataset properties.
      $metadata_obj = json_decode($metadata_string);
      $referencer = Drupal::service("dkan_data.value_referencer");
      $metadata_obj = $referencer->dereference($metadata_obj);
      $entity->set('field_json_metadata', json_encode($metadata_obj));
    }
  }

}

/**
 * Implements hook_entity_presave().
 */
function dkan_data_entity_presave(EntityInterface $entity) {

  if ($entity->bundle() != "data") {
    return;
  }

  if ($entity->get('field_data_type')->value != 'dataset') {
    return;
  }

  $entityType = $entity->getEntityTypeId();

  $metadata = json_decode($entity->get('field_json_metadata')->value);

  $title = isset($metadata->title) ? $metadata->title : $metadata->name;
  if ($entityType == 'node') {
    $entity->setTitle($title);
    if (empty($entity->field_data_type->value)) {
      $entity->field_data_type->value = "dataset";
    }
    $created = new DateTime();
    $created->setTimestamp($entity->getCreatedTime());
    $metadata->created = $created->format('Y-m-d\TH:i:s');

    $changed = new DateTime();
    $changed->setTimestamp($entity->getChangedTime());
    $metadata->modified = $changed->format('Y-m-d\TH:i:s');
  }

  // If there is no uuid add one.
  if (!isset($metadata->identifier)) {
    $metadata->identifier = $entity->uuid();
  }
  // If one exists in the uui it should be the same in the table.
  else {
    $entity->set('uuid', $metadata->identifier);
  }

  $referencer = Drupal::service("dkan_data.value_referencer");
  $metadata = $referencer->reference($metadata);
  $entity->set('field_json_metadata', json_encode($metadata));

  // If updating an existing entity, check for orphan property references.
  if (isset($entity->original)) {
    $referencer->processUpdatedDataset(
      $entity->referenced_metadata,
      $entity->get('field_json_metadata')->value
    );
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function dkan_data_node_predelete(EntityInterface $entity) {
  // Check for orphan references when datasets are deleted.
  if ($entity->bundle() == 'data' && $entity->get('field_data_type')->value == 'dataset') {
    $referenced_dataset = json_decode($entity->referenced_metadata);
    $referencer = Drupal::service("dkan_data.value_referencer");
    $referencer->processDeletedDataset($referenced_dataset);
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function dkan_data_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'data') {
    if (isset($fields['field_json_metadata'])) {
      $fields['field_json_metadata']->addConstraint('ProperJson', []);
    }
  }
}
