<?php

namespace Drupal\Tests\dkan_datastore\Unit\Controller;

use Drupal\Core\Entity\EntityStorageException;
use Drupal\dkan_common\Tests\DkanTestBase;
use Drupal\dkan_datastore\Service\Datastore;
use Drupal\Core\Entity\EntityRepository;
use Drupal\Core\Logger\LoggerChannelInterface;
use Drupal\dkan_datastore\Controller\Api;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Database\Connection;
use Drupal\Core\TypedData\TypedDataInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Database\Schema;
use Drupal\Core\Database\StatementInterface;
use Drupal\Core\Database\Query\SelectInterface;

/**
 * @coversDefaultClass Drupal\dkan_datastore\Controller\Datastore
 * @group              dkan_datastore
 */
class DatastoreApiTest extends DkanTestBase {

  private $noNode = FALSE;

  /**
   *
   */
  public function getContainer() {
    // TODO: Change the autogenerated stub.
    parent::setUp();
    $container = $this->getMockBuilder(ContainerInterface::class)
      ->setMethods(['get'])
      ->disableOriginalConstructor()
      ->getMockForAbstractClass();
    $container->method('get')
      ->with($this->logicalOr($this->equalTo('dkan_datastore.service')))
      ->will($this->returnCallback([$this, 'containerGet']));
    return $container;
  }

  /**
   *
   */
  public function containerGet($serviceName) {
    switch ($serviceName) {
      case 'dkan_datastore.service':
        $mockEntityRepository = $this->mockEntityRepository(EntityRepository::class);
        $mockLogger = $this->createMock(LoggerChannelInterface::class);
        $mockConnection = $this->getConnectionMock();
        return new Datastore($mockEntityRepository, $mockLogger, $mockConnection);
    }
  }

  /**
   *
   */
  private function getConnectionMock() {
    $mock = $this->getMockBuilder(Connection::class)
      ->disableOriginalConstructor()
      ->setMethods(['schema', 'query', 'select'])
      ->getMockForAbstractClass();

    $mock->method('schema')->willReturn($this->getSchemaMock());
    $mock->method('query')->willReturn($this->getStatementMock());
    $mock->method('select')->willReturn($this->getSelectMock());

    return $mock;
  }

  /**
   *
   */
  private function getSelectMock() {
    $mock = $this->getMockBuilder(SelectInterface::class)
      ->disableOriginalConstructor()
      ->setMethods(['countQuery', 'execute'])
      ->getMockForAbstractClass();

    $mock->method('countQuery')->willReturn($mock);
    $mock->method('execute')->willReturn($this->getStatementMock());

    return $mock;
  }

  /**
   *
   */
  private function getStatementMock() {
    $mock = $this->getMockBuilder(StatementInterface::class)
      ->disableOriginalConstructor()
      ->setMethods(['fetchAll', 'fetchField'])
      ->getMockForAbstractClass();

    $mock->method('fetchAll')->willReturn([(object) ['Field' => 'field_1'], (object) ['Field' => 'field_2']]);
    $mock->method('fetchField')->willReturn(2);

    return $mock;
  }

  /**
   *
   */
  private function getSchemaMock() {
    $mock = $this->getMockBuilder(Schema::class)
      ->disableOriginalConstructor()
      ->setMethods(['tableExists'])
      ->getMockForAbstractClass();

    $mock->method('tableExists')->willReturn(TRUE);

    return $mock;
  }

  /**
   *
   */
  private function mockEntityRepository() {
    $mock = $this->getMockBuilder(EntityRepository::class)
      ->setMethods(['loadEntityByUuid'])
      ->disableOriginalConstructor()
      ->getMock();

    $node = $this->mockNodeInterface();

    if ($this->noNode) {
      $mock->method('loadEntityByUuid')->willThrowException(new EntityStorageException("You Failed"));
    }
    else {
      $mock->method('loadEntityByUuid')
        ->willReturn($node);
    }

    return $mock;
  }

  /**
   *
   */
  private function mockNodeInterface() {
    $mock = $this->getMockBuilder(NodeInterface::class)
      ->setMethods(['get'])
      ->disableOriginalConstructor()
      ->getMockForAbstractClass();

    $node = $this->mockFieldItemListInterface();

    $mock->method('get')
      ->willReturn($node);

    return $mock;
  }

  /**
   *
   */
  private function mockFieldItemListInterface() {
    $mock = $this->getMockBuilder(FieldItemListInterface::class)
      ->setMethods(['get'])
      ->disableOriginalConstructor()
      ->getMockForAbstractClass();

    $list = $this->mockTypedDataInterface();

    $mock->method('get')
      ->willReturn($list);

    return $mock;
  }

  /**
   *
   */
  private function mockTypedDataInterface() {
    $mock = $this->getMockBuilder(TypedDataInterface::class)
      ->setMethods(['getValue'])
      ->disableOriginalConstructor()
      ->getMockForAbstractClass();

    $data = [
      'value' => json_encode(['data' => ['downloadURL' => 'http://google.com']]),
    ];

    $mock->method('getValue')
      ->willReturn($data);

    return $mock;
  }

  /**
   * Tests Construct().
   */
  public function testSummary() {
    $controller = Api::create($this->getContainer());
    $response = $controller->summary('asdbv');
    $this->assertEquals('{"numOfColumns":2,"columns":["field_1","field_2"],"numOfRows":2}', $response->getContent());
  }

  /**
   *
   */
  public function testImport() {
    $controller = Api::create($this->getContainer());
    $response = $controller->import('asdbv');
    $this->assertEquals('{"identifier":"asdbv"}', $response->getContent());
  }

  /**
   *
   */
  public function testImportFailure() {
    $this->noNode = TRUE;
    $controller = Api::create($this->getContainer());
    $this->noNode = FALSE;
    $response = $controller->import('asdbv');
    $this->assertEquals('{"message":"You Failed"}', $response->getContent());
  }

  /**
   *
   */
  public function testDelete() {
    $controller = Api::create($this->getContainer());
    $response = $controller->delete('asdbv');
    $this->assertEquals('{"identifier":"asdbv"}', $response->getContent());
  }

}
