version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone --single-branch --depth 1 --branch clean-dkan-test-coverage https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Initialize Project
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            mkdir ~/sandbox
            cd ~/sandbox
            dktl init
      - run:
          name: Get Drupal
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl get 8.7.5
      - run:
          name: Make DKAN
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            sudo chmod 777 src/make/composer.json
            bash -c 'if [[ -z "${CIRCLE_PR_USERNAME}" ]]; then                                                                                                                             !6354
              sudo echo "{\"description\":\"Project\",\"minimum-stability\":\"dev\",\"repositories\":[{\"type\":\"vcs\",\"url\":\"https://github.com/fmizzell/json_form\"},{\"type\":\"composer\",\"url\":\"https://asset-packagist.org\"}],\"require\":{\"getdkan/dkan2\":\"dev-$CIRCLE_BRANCH\"}}" > src/make/composer.json
            else
              CIRCLE_PR_BRANCH=`curl -s https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER} | jq -r '.head.ref'`
              sudo echo "{\"description\":\"Project\",\"minimum-stability\":\"dev\",\"repositories\":[{\"type\":\"vcs\",\"url\":\"https://github.com/$CIRCLE_PR_USERNAME/dkan2\"},{\"type\":\"vcs\",\"url\":\"https://github.com/fmizzell/json_form\"},{\"type\":\"vcs\",\"url\":\"https://github.com/civicactions/lunr.php\"},{\"type\":\"composer\",\"url\":\"https://asset-packagist.org\"}],\"require\":{\"getdkan/dkan2\":\"dev-$CIRCLE_PR_BRANCH\"}}" > src/make/composer.json
            fi'
            cat src/make/composer.json
            dktl make
            dktl updatedrush -y
            rm -rf ./docroot/profiles/contrib/dkan2
            mv ~/project ./docroot/profiles/contrib/dkan2
            ls -lha ./docroot/profiles/contrib/dkan2
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl install
      - run:
          name: Run phpUnit tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl xdebug:start
            dktl dkan:test-phpunit-coverage $CC_TEST_REPORTER_ID
            echo $?
      - run:
          name: Run cypress tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/sandbox
            dktl drush user:create testuser --password="2jqzOAnXS9mmcLasy"
            dktl drush user-add-role api_user testuser
            dktl drush dkan-dummy-content:create
            dktl drush dkan-datastore:import c9e2d352-e24c-4051-9158-f48127aa5692
            dktl drush dkan-datastore:import 5dc1cfcf-8028-476c-a020-f58ec6dd621c
            dktl dkan:test-cypress
      - store_artifacts:
          path: ~/sandbox/docroot/profiles/contrib/dkan2/cypress/screenshots
      - store_test_results:
          path: ~/sandbox/docroot/profiles/contrib/dkan2/cypress/videos
