version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone --single-branch --branch master https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Initialize Project
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/project
            dktl init
      - run:
          name: Get Drupal
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/project
            dktl get 8.6.14
      - run:
          name: Make DKAN
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/project
            sudo chmod 777 src/make/composer.json
            sudo echo "{\"description\":\"Project\",\"minimum-stability\":\"dev\",\"repositories\":[{\"type\":\"vcs\",\"url\":\"https://github.com/fmizzell/json_form\"},{\"type\":\"composer\",\"url\":\"https://asset-packagist.org\"}],\"require\":{\"getdkan/dkan2\":\"dev-$CIRCLE_BRANCH\"}}" > src/make/composer.json
            dktl make
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl install

      - run:
          name: Run phpUnit tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl dkan:test-phpunit

      - run:
          name: Run cypress tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl dkan:test-cypress

