version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
    steps:
      - checkout
      - run:
          name: Package DKAN
          command: |
            mkdir /home/circleci/dkan2
            mv /home/circleci/project/* /home/circleci/dkan2
            ls -lha /home/circleci/dkan2
            ls -lha /home/circleci/project
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone -b dkan2 https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Initialize project
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
            cd ~/project
            dktl init
            ls -lha /home/circleci/project

