version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: ubuntu:16.04
    working_directory: /www
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updates etc
          command: |
            apt-get update
            apt-get upgrade -y
            apt-get install git curl wget ruby language-pack-en-base libdigest-hmac-perl -y
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone -b dkan2 https://github.com/GetDKAN/dkan-tools.git
            ln -s ~/dkan-tools/bin/dktl /usr/local/bin/dktl
            chmod +x /usr/local/bin/dktl
      - run:
          name: Install DKAN
          command: |
            touch /var/www/dktl.yml
            dktl