version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: Install DKTL
          command: |
            cd ~
            ls -lha ./project

