version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
    steps:
      - checkout
      - run:
          name: Updates etc
          command: |
            ls -lha