version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
    steps:
      - checkout
      - run:
          name: Package DKAN
          command: |
            mkdir /home/circleci/dkan2
            mv /home/circleci/project/* /home/circleci/dkan2
            ls -lha /home/circleci/dkan2
            ls -lha /home/circleci/project
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone -b dkan2 https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
            cd ~/project
            cp -r ~/dkan2/cypress .
            cp -r ~/dkan2/cypress.json .
            dktl init
            dktl drupal:get 8.6.3
            dktl drupal:make
            dktl drush site-install -y --notify
            ls -lha
            ls -la docroot/profiles
      - run:
          name: Run tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
            dktl
            dktl test:cypress



