version: 2
jobs:
  build:
    parallelism: 1
    machine:
      image: circleci/classic:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      DKTL_CHOWN: False
      DRUPAL_VERSION: V8
    steps:
      - checkout
      - run:
          name: Package DKAN
          command: |
            mkdir /home/circleci/dkan2
            mv /home/circleci/project/* /home/circleci/dkan2
      - run:
          name: Install DKTL
          command: |
            cd ~
            git clone --single-branch --branch dkan-tests https://github.com/GetDKAN/dkan-tools.git
            chmod 777 ./dkan-tools/bin/dktl
            export PATH=$PATH:~/dkan-tools/bin
            which dktl
      - run:
          name: Make DKAN
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cd ~/project
            cp -r ~/dkan2/cypress .
            cp ~/dkan2/cypress.json .
            dktl init
            sudo chmod 777 src/make/composer.json
            sudo echo "{\"description\":\"Project\",\"minimum-stability\":\"dev\",\"repositories\":[{\"type\":\"vcs\",\"url\":\"https://github.com/getdkan/dkan2\"},{\"type\": \"vcs\", \"url\": \"https://github.com/fmizzell/sae\"},{\"type\": \"vcs\", \"url\": \"https://github.com/fmizzell/datastore\"},{\"type\":\"composer\",\"url\":\"https://asset-packagist.org\"}],\"require\":{\"getdkan/dkan2\":\"dev-$CIRCLE_BRANCH\"}}" > src/make/composer.json
            dktl drupal:get 8.6.4
            dktl drupal:make
      - run:
          name: Install site
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl drush site-install dkan2 -y
      - run:
          name: Run cypress tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            dktl dkan:test-cypress
      - run:
          name: Run phpUnit tests
          command: |
            export PATH=$PATH:~/dkan-tools/bin
            cp ../dkan2/phpunit.xml .
            dktl dkan:test-phpunit

